name: simple_flame_game
description: "A new Flutter project."


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  bloc: ^8.1.2
  collection: ^1.18.0
  cupertino_icons: ^1.0.2
  flame: ^1.14.0
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/jet/
    - assets/fire/
    - assets/common/
    - assets/missiles/
    - assets/explosion/
    - assets/background/

